#!/bin/sh

brew bundle --file=/dev/stdin <<EOF

tap "gromgit/homebrew-fuse"
tap "hashicorp/tap"
tap "jorgelbg/tap"
tap "lyraphase/pcloud"
tap "qmk/qmk"

brew "bat"
brew "gh"
brew "git-secret"
brew "git"
brew "gromgit/homebrew-fuse/gocryptfs-mac"
brew "hashicorp/tap/terraform"
brew "helm"
brew "htop"
brew "kubectx"
brew "kubernetes-cli"
brew "mas"
brew "minikube"
brew "mtr"
brew "mysql-client"
brew "picocom"
brew "qmk/qmk/qmk"
brew "tilt"
brew "tmux"
brew "vim"
brew "wget"
brew "wireguard-tools"
brew "zstd"

cask "1password"
cask "beekeeper-studio"
cask "discord"
cask "font-source-code-pro"
cask "gcloud-cli"
cask "ghostty"
cask "halloy"
cask "iina"
cask "lyraphase/pcloud/pcloud-drive"
cask "macfuse"
cask "ngrok"
cask "orbstack"
cask "postman"
cask "proton-mail"
cask "protonvpn"
cask "prusaslicer"
cask "rectangle"
cask "scroll-reverser"
cask "signal"
cask "slack"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "zed"
cask "zoom"

EOF
