#!/bin/sh

brew bundle --file=/dev/stdin <<EOF

tap "hashicorp/tap"
tap "lyraphase/pcloud"
tap "qmk/qmk"

brew "gh"
brew "git-secret"
brew "git"
brew "hashicorp/tap/terraform"
brew "helm"
brew "htop"
brew "kubectx"
brew "kubernetes-cli"
brew "minikube"
brew "mtr"
brew "picocom"
brew "pinentry-mac"
brew "qmk"
brew "tilt"
brew "tmux"
brew "vim"
brew "wget"
brew "wireguard-tools"
brew "zstd"

cask "1password"
cask "alt-tab"
cask "beekeeper-studio"
cask "discord"
cask "font-source-code-pro"
cask "gcloud-cli"
cask "halloy"
cask "inkscape"
cask "iterm2"
cask "ngrok"
cask "orbstack"
cask "passepartout"
cask "pcloud-drive"
cask "postman"
cask "proton-mail"
cask "protonvpn"
cask "prusaslicer"
cask "raycast"
cask "rectangle"
cask "signal"
cask "slack"
cask "spotify"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "zoom"

EOF
