#!/usr/bin/env bash
#
# {{ ansible_managed }}

if [ $(id -u) -ne 0 ]; then 
  echo ""
  echo "Backup must be run as root to include top-level directories:"
  echo "  example: sudo -E backup"
  exit
fi

restic backup -o b2.connections=32 \
              --exclude-caches \
              --exclude=/home/winston/Documents \
              --exclude=/home/winston/.cache \
              --exclude=/home/winston/pCloudDrive \
              --exclude=/home/winston/Dropbox\ \(Phobio\) \
              --exclude=/var/lib/docker/volumes \
              --exclude={/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp} \
              /
