#!/usr/bin/env bash
#
# {{ ansible_managed }}

if [ $(id -u) -ne 0 ]; then
  echo ""
  echo "Backup must be run as root to include top-level directories:"
  echo "  example: sudo backup"
  exit
fi

export RESTIC_PASSWORD="{{ restic_password }}"
export RESTIC_REPOSITORY="s3:s3.us-west-004.backblazeb2.com/{{ restic_repository }}"
export AWS_ACCESS_KEY_ID="{{ backblaze_account_id }}"
export AWS_SECRET_ACCESS_KEY="{{ backblaze_account_key }}"

restic backup \
  -o s3.connections=10 \
  --one-file-system \
  --exclude-caches \
  --exclude=/home/winston/Documents \
  --exclude=/home/winston/.cache \
  --exclude=/home/winston/pCloudDrive \
  --exclude=/var/lib/docker/volumes \
  --exclude=/home/winston/.config/Slack/Cache \
  --exclude=/home/winston/.pcloud \
  / /boot

unset RESTIC_PASSWORD
unset RESTIC_REPOSITORY
unset B2_ACCOUNT_ID
unset B2_ACCOUNT_KEY
