#!/usr/bin/env bash
#
# Wrapper for gocryptfs
# Mount gocryptfs-encrypted filesystem As Local Directory
# Copyright (c) Winston Astrachan, 2020


LOCKFILE=/var/run/user/$UID/gocryptfs_mounted
MOUNT_PATH=~
ENCRYPTED_STORAGE=~/.encrypted


# Test for gocryptfs
if [[ ! -x "$(command -v gocryptfs)" ]]; then
    echo "Error: gocryptfs is not installed."
    exit 1
fi

# Test for encrypted dir storage
if [[ ! -d "$ENCRYPTED_STORAGE" ]]; then
    echo "Creating encrypted folder storage at $ENCRYPTED_STORAGE"
    mkdir $ENCRYPTED_STORAGE
fi

# Select folder to mount
echo "Select a directory to mount:"
echo ""
cd $ENCRYPTED_STORAGE
dirs=(*)
for dir in "${!dirs[@]}"; do
    echo "    [$dir] ${dirs[$dir]}"
done
echo "    [c] Create New"
read selection
if [[ "$selection" == "c" ]]; then
    echo "Directory name?"
    read selected_dir
    mkdir "$selected_dir"
else
    selected_dir="${dirs[$selection]}"
fi

# Create mountpoint
if [[ ! -d "$MOUNT_PATH/$selected_dir" ]]; then
    mkdir -p "$MOUNT_PATH/$selected_dir"
fi

# Mount directory
gocryptfs "$ENCRYPTED_STORAGE/$selected_dir" "$MOUNT_PATH/$selected_dir"
echo $selected_dir >> $LOCKFILE
echo "Mounted $MOUNT_PATH/$selected_dir"
