#!/usr/bin/env bash
#
# Swap audio output sinks
# Change between multiple pulseaudio sinks, defined in SOURCE_KEYWORDS
# Copyright (c) Winston Astrachan, 2020


SOURCE_KEYWORDS=("Bose_PC_Desktop_Controller" "alsa_output.pci-0000_00_1f.3.analog-stereo")
INDEX_GREP="grep -oP '^\s+\*?\s+index: +\K([0-9]+)$'"
INUSE_GREP="grep -oP '^\s+\*\s+index: [0-9]+$'"
SINKS="$(pacmd list-sinks)"


for source in ${SOURCE_KEYWORDS[@]}; do
    source_pacmd="$(echo "$SINKS" | grep -B 1 $source)"
    source_index="$(echo "$source_pacmd" | eval $INDEX_GREP)"
    source_inuse="$(echo "$source_pacmd" | eval $INUSE_GREP)"

    if [[ -z "$source_inuse" ]]; then
        pacmd set-default-sink $source_index
    fi

done
