#!/usr/bin/env bash
#
# Wrapper for encfs
# Unmount all mounted encfs directories
# Copyright (c) Winston Astrachan, 2020


LOCKFILE=/var/run/user/$UID/encfs_mounted
MOUNT_PATH=/mnt


if [[ -f $LOCKFILE ]]; then
    while IFS= read -r line
    do
        sudo umount $MOUNT_PATH/$line
        sudo rm -r $MOUNT_PATH/$line
        echo "Unmounted $MOUNT_PATH/$line"
    done < "$LOCKFILE"
    rm $LOCKFILE
fi
