#!/usr/bin/env bash
#
# Wrapper for gocryptfs
# Unmount all mounted gocryptfs directories
# Copyright (c) Winston Astrachan, 2020


LOCKFILE=/var/run/user/$UID/gocryptfs_mounted
MOUNT_PATH=~


if [[ -f $LOCKFILE ]]; then
    while IFS= read -r line
    do
        fusermount -u $MOUNT_PATH/$line
        rm -r $MOUNT_PATH/$line
        echo "Unmounted $MOUNT_PATH/$line"
    done < "$LOCKFILE"
    rm $LOCKFILE
fi
