---

- name: Update dotfiles configuration
  hosts: all
  become: false
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: zsh
      tags: [zsh]
    - role: vim
      tags: [dev, server, vim]
    - role: tmux
      tags: [tmux]
    - role: git
      tags: [dev, git]
    - role: pyenv
      tags: [dev, pyenv]
