---

- name: Update dotfiles configuration
  hosts: all
  become: false
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: zsh
    - role: vim
      tags: [dev, server]
    - role: tmux
    - role: git
      tags: [dev]
    - role: pyenv
      tags: [dev]
    - role: ssh
      tags: [dev]
    - role: gpg
      tags: [dev]
