---

- name: Update SSH directory
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Update SSH config files
  template:
    src: files/ssh/{{ item }}.j2
    dest: ~/.ssh/{{ item }}
    mode: '0644'
  loop:
    - config
    - config_cisco

- name: Update SSH public key(s)
  copy:
    content: "{{ item.public_key }}"
    dest: "~/.ssh/{{ item.name }}.pub"
    mode: '0644'
  with_items: "{{ ssh_keys }}"

- name: Update SSH private key(s)
  copy:
    content: "{{ item.private_key }}"
    dest: "~/.ssh/{{ item.name }}"
    mode: '0600'
  with_items: "{{ ssh_keys }}"
