---

- name: create dotfiles directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.zshrc.d
    - ~/.zprofile.d
  tags: [dev, server]

- name: update zshrc and zprofile
  template:
    src: "files/{{ item }}.j2"
    dest: "~/.{{ item }}"
  loop:
    - zshrc
    - zprofile
    - profile
  tags: [dev, server]

- name: update base zshrc.d files
  template:
    src: "files/zshrc.d/{{item}}.j2"
    dest: "~/.zshrc.d/{{item}}.zsh"
  loop:
    - 10-omz
    - 12-spaceship
    - 20-environment
    - 30-aliases
  tags: [dev, server]

- name: update development zshrc.d files
  template:
    src: "files/zshrc.d/{{item}}.j2"
    dest: "~/.zshrc.d/{{item}}.zsh"
  loop:
    - 31-aliases-dev
    - 40-pyenv
    - 41-nvm
  tags: [dev]

- name: update base zprofile.d files
  template:
    src: "files/zprofile.d/{{item}}.j2"
    dest: "~/.zprofile.d/{{item}}.zsh"
  loop:
    - 10-environment
    - 11-path
  tags: [dev, server]

- name: update development zprofile.d files
  template:
    src: "files/zprofile.d/{{item}}.j2"
    dest: "~/.zprofile.d/{{item}}.zsh"
  loop:
    - 20-pyenv
  tags: [dev]

- name: download kubectx completions
  get_url:
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/{{ item }}"
    dest: "~/.oh-my-zsh/completions/_{{ item }}"
    mode: 0755
  loop:
    - _kubectx.zsh
    - _kubens.zsh
  tags: [dev]

# completions renamed to be prefixed with underscore, upstream
# remove old completions to prevent future conflict
- name: remove old kubectx completions
  file:
    path: "~/.oh-my-zsh/completions/_{{ item }}"
    state: absent
  loop:
    - kubectx.zsh
    - kubens.zsh
  tags: [dev]

- name: remove zshrc.d files
  file:
    path: "~/.zshrc.d/{{ item }}.zsh"
    state: absent
  loop:
    - 11-path
    - 42-kubectx
  tags: [dev, server]

- name: remove zprofile.d files
  file:
    path: "~/.zprofile.d/{{ item }}.zsh"
    state: absent
  loop: []
  tags: [dev, server]
