---

- name: Create dotfiles directory
  file:
    path: ~/.zshrc.d
    state: directory
  tags: [dev, server]

- name: Update zshrc
  template:
    src: files/zshrc.j2
    dest: ~/.zshrc
  tags: [dev, server]

- name: Update base zsh dotfiles
  template:
    src: "files/zshrc.d/{{item}}.j2"
    dest: "~/.zshrc.d/{{item}}.zsh"
  loop:
    - 10-omz
    - 11-path
    - 12-spaceship
    - 20-environment
    - 30-aliases
  tags: [dev, server]

- name: Update development zsh dotfiles
  template:
    src: "files/zshrc.d/{{item}}.j2"
    dest: "~/.zshrc.d/{{item}}.zsh"
  loop:
    - 31-aliases-dev
    - 40-pyenv
  tags: [dev]

- name: Remove zsh dotfiles
  file:
    path: "~/.zshrc.d/{{ item }}.zsh"
    state: absent
  loop:
    - 42-kubectl
  tags: [dev, server]
