---
- name: Include shell configuration tasks
  ansible.builtin.include_tasks: shell.yml
  tags: [server, dev]

- name: Include prompt configuration tasks
  ansible.builtin.include_tasks: prompt.yml
  tags: [server, dev]

- name: Include dotfiles configuration tasks
  ansible.builtin.include_tasks: dotdir.yml
  tags: [server, dev]

- name: Include script configuration tasks
  ansible.builtin.include_tasks: scripts.yml
  tags: [dev]
