---
- name: Update Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    clone: true
    update: true
    accept_hostkey: true
    version: master
  tags: [dev, server]

- name: Create oh-my-zsh completions dir
  ansible.builtin.file:
    dest: "~/.oh-my-zsh/completions/"
    state: directory
    mode: "0755"
    recurse: true
  tags: [dev, server]

- name: Update spaceship
  ansible.builtin.git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
    clone: true
    update: true
    accept_hostkey: true
    version: master
  tags: [dev, server]

- name: Link spaceship
  ansible.builtin.file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link
  tags: [dev, server]
