---

- name: update Oh My Zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    clone: yes
    update: yes
    accept_hostkey: yes
  tags: [dev, server]

- name: create oh-my-zsh completions dir
  file:
    dest: "~/.oh-my-zsh/completions/"
    state: directory
    recurse: true
  tags: [dev, server]

- name: update spaceship
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
    clone: yes
    update: yes
    accept_hostkey: yes
  tags: [dev, server]

- name: link spaceship
  file:
    src: ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link
  tags: [dev, server]
