---

- name: install utility scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: a+x
  become: true
  with_fileglob:
    - files/scripts/*
  tags: [dev]

- name: delete old scripts
  file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  become: true
  loop:
    - mount_encfs
    - unmount_encfs
    - swap_sink
  tags: [dev]
