---

- name: locate path to ZSH
  find:
    paths:
      - /usr/local/bin/
      - /usr/bin/
      - /bin/
    patterns: zsh
    follow: yes
    file_type: any
  register: zsh_binary
  tags: [dev, server]

- name: change default shell to ZSH
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_binary.files[0].path }}"
  become: true
  when:
    - zsh_binary.files|length > 0
    - ansible_system == "Darwin"
  tags: [dev, server]

- name: change default shell to ZSH
  command: chsh -s {{ zsh_binary.files[0].path }}
  become: true
  when:
    - zsh_binary.files|length > 0
    - ansible_system == "Linux"
  tags: [dev, server]
