---
- name: Locate path to ZSH
  ansible.builtin.find:
    paths:
      - /usr/local/bin/
      - /usr/bin/
      - /bin/
    patterns: zsh
    follow: true
    file_type: any
  register: zsh_binary
  tags: [dev, server]

- name: Change default shell to ZSH
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_binary.files[0].path }}"
  become: true
  when:
    - zsh_binary.files|length > 0
    - ansible_system == "Darwin"
  tags: [dev, server]

- name: Cange default shell to ZSH
  ansible.builtin.command: chsh -s {{ zsh_binary.files[0].path }}
  become: true
  when:
    - zsh_binary.files|length > 0
    - ansible_system == "Linux"
  changed_when: false
  tags: [dev, server]
