---
- name: Update tmux config
  ansible.builtin.template:
    src: files/tmux.conf.j2
    dest: ~/.tmux.conf
    mode: "0644"
  tags: [dev, server]

- name: Create tmux plugin directory
  ansible.builtin.file:
    path: ~/.tmux/plugins/
    state: directory
    mode: "0755"
  when: tmux_use_tpm
  tags: [dev, server]

- name: Update tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: master
    clone: true
    update: true
  when: tmux_use_tpm
  tags: [dev, server]

- name: Delete tmuxinator config directory
  ansible.builtin.file:
    path: ~/.config/tmuxinator
    state: absent
