---

- name: Update tmux config
  template:
    src: files/tmux.conf.j2
    dest: ~/.tmux.conf
  tags: [dev, server]

- name: Create tmux plugin directory
  file:
    path: ~/.tmux/plugins/
    state: directory
  when: tmux_use_tpm
  tags: [dev, server]

- name: Update tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    clone: true
    update: true
  when: tmux_use_tpm
  tags: [dev, server]

- name: Delete tmuxinator config directory
  file:
    path: ~/.config/tmuxinator
    state: absent
