---

- name: Update pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    clone: yes
    update: yes

- name: Remove pyenv-virtualenv
  file:
    path: ~/.pyenv/plugins/pyenv-virtualenv
    state: absent
