---
- name: Install .vimrc
  ansible.builtin.template:
    src: files/vimrc.j2
    dest: ~/.vimrc
    mode: "0644"

- name: Create Vim bundle directory
  ansible.builtin.file:
    path: ~/.vim/bundle/
    state: directory
    mode: "0755"

- name: Update Vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    clone: true
    update: true
    version: master
  when: vim_use_vundle

- name: Update Vim plugins
  ansible.builtin.command: vim +PluginInstall +qall
  when: vim_use_vundle
  changed_when: false
