---

- name: Test for gpg key
  shell: gpg --list-secret-keys
  register: gpg_test
  when: gpg_key is not none

- name: Import gpg key
  shell: |
    echo '{{ gpg_key }}' | gpg --import --allow-secret-key-import --batch -
  register: gpg_import
  when:
    - gpg_key is not none
    - gpg_test.stdout is not search(gpg_signature)

- name: Trust gpg key
  shell: |
    expect -c '
      spawn gpg --edit-key {{ gpg_signature }} trust quit
      expect "Your decision? "
      send -- "5\r"
      expect "Do you really want to set this key to ultimate trust? (y/N) "
      send -- "y\r"
      expect eof
    '
  when:
    - gpg_key is not none
    - gpg_test.stdout is not search(gpg_signature)
    - "{{ gpg_import.stderr is search('imported: 1') }}"
