---
- name: Check existing GPG keys
  ansible.builtin.shell: gpg --list-secret-keys --with-colons
  register: gpg_test
  when: gpg_keys is defined and gpg_keys is not none
  changed_when: false

- name: Import GPG private key
  ansible.builtin.shell: |
    gpg --batch --import <<EOF
    {{ item.key }}
    EOF
  register: import_result
  when:
    - gpg_keys is defined and gpg_keys is not none
    - item.signature not in gpg_test.stdout
  loop: "{{ gpg_keys }}"
  no_log: true

- name: Import owner trust
  ansible.builtin.shell: |
    echo "{{ item.signature }}:6:" | gpg --import-ownertrust
  when:
    - gpg_keys is defined and gpg_keys is not none
    - item.signature not in gpg_test.stdout
  loop: "{{ gpg_keys }}"
  no_log: true

- name: Update gpg configuration
  ansible.builtin.template:
    src: gpg.conf.j2
    mode: "0644"
    dest: ~/.gnupg/gpg.conf

- name: Update gpg agent configuration
  ansible.builtin.copy:
    src: gpg-agent.conf
    mode: "0644"
    dest: ~/.gnupg/gpg-agent.conf
  notify: Restart gpg-agent
